blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Feature Requests & Questions
    url: https://github.com/antvis/X6/discussions
    about: Please ask and answer questions here â†’
  - name: ğŸ’¬ æå‡ºæ–°åŠŸèƒ½å¹¶æå‡ºé—®é¢˜
    url: https://github.com/antvis/X6/discussions
    about: åœ¨æ­¤æé—®å¹¶åœ¨æ­¤å¤„åˆ†äº«æ‚¨çš„ç­”æ¡ˆâ†’
